/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 4.1.3
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ReturnDataRelationshipsReturnLineItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReturnDataRelationshipsReturnLineItems{}

// ReturnDataRelationshipsReturnLineItems struct for ReturnDataRelationshipsReturnLineItems
type ReturnDataRelationshipsReturnLineItems struct {
	Data *ReturnDataRelationshipsReturnLineItemsData `json:"data,omitempty"`
}

// NewReturnDataRelationshipsReturnLineItems instantiates a new ReturnDataRelationshipsReturnLineItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnDataRelationshipsReturnLineItems() *ReturnDataRelationshipsReturnLineItems {
	this := ReturnDataRelationshipsReturnLineItems{}
	return &this
}

// NewReturnDataRelationshipsReturnLineItemsWithDefaults instantiates a new ReturnDataRelationshipsReturnLineItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnDataRelationshipsReturnLineItemsWithDefaults() *ReturnDataRelationshipsReturnLineItems {
	this := ReturnDataRelationshipsReturnLineItems{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ReturnDataRelationshipsReturnLineItems) GetData() ReturnDataRelationshipsReturnLineItemsData {
	if o == nil || IsNil(o.Data) {
		var ret ReturnDataRelationshipsReturnLineItemsData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnDataRelationshipsReturnLineItems) GetDataOk() (*ReturnDataRelationshipsReturnLineItemsData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ReturnDataRelationshipsReturnLineItems) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ReturnDataRelationshipsReturnLineItemsData and assigns it to the Data field.
func (o *ReturnDataRelationshipsReturnLineItems) SetData(v ReturnDataRelationshipsReturnLineItemsData) {
	o.Data = &v
}

func (o ReturnDataRelationshipsReturnLineItems) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReturnDataRelationshipsReturnLineItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableReturnDataRelationshipsReturnLineItems struct {
	value *ReturnDataRelationshipsReturnLineItems
	isSet bool
}

func (v NullableReturnDataRelationshipsReturnLineItems) Get() *ReturnDataRelationshipsReturnLineItems {
	return v.value
}

func (v *NullableReturnDataRelationshipsReturnLineItems) Set(val *ReturnDataRelationshipsReturnLineItems) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnDataRelationshipsReturnLineItems) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnDataRelationshipsReturnLineItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnDataRelationshipsReturnLineItems(val *ReturnDataRelationshipsReturnLineItems) *NullableReturnDataRelationshipsReturnLineItems {
	return &NullableReturnDataRelationshipsReturnLineItems{value: val, isSet: true}
}

func (v NullableReturnDataRelationshipsReturnLineItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnDataRelationshipsReturnLineItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
