/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 3.0.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SkuResponseList struct for SkuResponseList
type SkuResponseList struct {
	Data []Data `json:"data,omitempty"`
}

// NewSkuResponseList instantiates a new SkuResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuResponseList() *SkuResponseList {
	this := SkuResponseList{}
	return &this
}

// NewSkuResponseListWithDefaults instantiates a new SkuResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuResponseListWithDefaults() *SkuResponseList {
	this := SkuResponseList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SkuResponseList) GetData() []Data {
	if o == nil || o.Data == nil {
		var ret []Data
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuResponseList) GetDataOk() ([]Data, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SkuResponseList) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Data and assigns it to the Data field.
func (o *SkuResponseList) SetData(v []Data) {
	o.Data = v
}

func (o SkuResponseList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableSkuResponseList struct {
	value *SkuResponseList
	isSet bool
}

func (v NullableSkuResponseList) Get() *SkuResponseList {
	return v.value
}

func (v *NullableSkuResponseList) Set(val *SkuResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuResponseList(val *SkuResponseList) *NullableSkuResponseList {
	return &NullableSkuResponseList{value: val, isSet: true}
}

func (v NullableSkuResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
