/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 3.0.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// MarketResponseDataRelationships struct for MarketResponseDataRelationships
type MarketResponseDataRelationships struct {
	Merchant       *MarketResponseDataRelationshipsMerchant                        `json:"merchant,omitempty"`
	PriceList      *MarketResponseDataRelationshipsPriceList                       `json:"price_list,omitempty"`
	InventoryModel *InventoryReturnLocationResponseDataRelationshipsInventoryModel `json:"inventory_model,omitempty"`
	TaxCalculator  *MarketResponseDataRelationshipsTaxCalculator                   `json:"tax_calculator,omitempty"`
	CustomerGroup  *CustomerResponseDataRelationshipsCustomerGroup                 `json:"customer_group,omitempty"`
	Attachments    *AvalaraAccountResponseDataRelationshipsAttachments             `json:"attachments,omitempty"`
}

// NewMarketResponseDataRelationships instantiates a new MarketResponseDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketResponseDataRelationships() *MarketResponseDataRelationships {
	this := MarketResponseDataRelationships{}
	return &this
}

// NewMarketResponseDataRelationshipsWithDefaults instantiates a new MarketResponseDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketResponseDataRelationshipsWithDefaults() *MarketResponseDataRelationships {
	this := MarketResponseDataRelationships{}
	return &this
}

// GetMerchant returns the Merchant field value if set, zero value otherwise.
func (o *MarketResponseDataRelationships) GetMerchant() MarketResponseDataRelationshipsMerchant {
	if o == nil || o.Merchant == nil {
		var ret MarketResponseDataRelationshipsMerchant
		return ret
	}
	return *o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketResponseDataRelationships) GetMerchantOk() (*MarketResponseDataRelationshipsMerchant, bool) {
	if o == nil || o.Merchant == nil {
		return nil, false
	}
	return o.Merchant, true
}

// HasMerchant returns a boolean if a field has been set.
func (o *MarketResponseDataRelationships) HasMerchant() bool {
	if o != nil && o.Merchant != nil {
		return true
	}

	return false
}

// SetMerchant gets a reference to the given MarketResponseDataRelationshipsMerchant and assigns it to the Merchant field.
func (o *MarketResponseDataRelationships) SetMerchant(v MarketResponseDataRelationshipsMerchant) {
	o.Merchant = &v
}

// GetPriceList returns the PriceList field value if set, zero value otherwise.
func (o *MarketResponseDataRelationships) GetPriceList() MarketResponseDataRelationshipsPriceList {
	if o == nil || o.PriceList == nil {
		var ret MarketResponseDataRelationshipsPriceList
		return ret
	}
	return *o.PriceList
}

// GetPriceListOk returns a tuple with the PriceList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketResponseDataRelationships) GetPriceListOk() (*MarketResponseDataRelationshipsPriceList, bool) {
	if o == nil || o.PriceList == nil {
		return nil, false
	}
	return o.PriceList, true
}

// HasPriceList returns a boolean if a field has been set.
func (o *MarketResponseDataRelationships) HasPriceList() bool {
	if o != nil && o.PriceList != nil {
		return true
	}

	return false
}

// SetPriceList gets a reference to the given MarketResponseDataRelationshipsPriceList and assigns it to the PriceList field.
func (o *MarketResponseDataRelationships) SetPriceList(v MarketResponseDataRelationshipsPriceList) {
	o.PriceList = &v
}

// GetInventoryModel returns the InventoryModel field value if set, zero value otherwise.
func (o *MarketResponseDataRelationships) GetInventoryModel() InventoryReturnLocationResponseDataRelationshipsInventoryModel {
	if o == nil || o.InventoryModel == nil {
		var ret InventoryReturnLocationResponseDataRelationshipsInventoryModel
		return ret
	}
	return *o.InventoryModel
}

// GetInventoryModelOk returns a tuple with the InventoryModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketResponseDataRelationships) GetInventoryModelOk() (*InventoryReturnLocationResponseDataRelationshipsInventoryModel, bool) {
	if o == nil || o.InventoryModel == nil {
		return nil, false
	}
	return o.InventoryModel, true
}

// HasInventoryModel returns a boolean if a field has been set.
func (o *MarketResponseDataRelationships) HasInventoryModel() bool {
	if o != nil && o.InventoryModel != nil {
		return true
	}

	return false
}

// SetInventoryModel gets a reference to the given InventoryReturnLocationResponseDataRelationshipsInventoryModel and assigns it to the InventoryModel field.
func (o *MarketResponseDataRelationships) SetInventoryModel(v InventoryReturnLocationResponseDataRelationshipsInventoryModel) {
	o.InventoryModel = &v
}

// GetTaxCalculator returns the TaxCalculator field value if set, zero value otherwise.
func (o *MarketResponseDataRelationships) GetTaxCalculator() MarketResponseDataRelationshipsTaxCalculator {
	if o == nil || o.TaxCalculator == nil {
		var ret MarketResponseDataRelationshipsTaxCalculator
		return ret
	}
	return *o.TaxCalculator
}

// GetTaxCalculatorOk returns a tuple with the TaxCalculator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketResponseDataRelationships) GetTaxCalculatorOk() (*MarketResponseDataRelationshipsTaxCalculator, bool) {
	if o == nil || o.TaxCalculator == nil {
		return nil, false
	}
	return o.TaxCalculator, true
}

// HasTaxCalculator returns a boolean if a field has been set.
func (o *MarketResponseDataRelationships) HasTaxCalculator() bool {
	if o != nil && o.TaxCalculator != nil {
		return true
	}

	return false
}

// SetTaxCalculator gets a reference to the given MarketResponseDataRelationshipsTaxCalculator and assigns it to the TaxCalculator field.
func (o *MarketResponseDataRelationships) SetTaxCalculator(v MarketResponseDataRelationshipsTaxCalculator) {
	o.TaxCalculator = &v
}

// GetCustomerGroup returns the CustomerGroup field value if set, zero value otherwise.
func (o *MarketResponseDataRelationships) GetCustomerGroup() CustomerResponseDataRelationshipsCustomerGroup {
	if o == nil || o.CustomerGroup == nil {
		var ret CustomerResponseDataRelationshipsCustomerGroup
		return ret
	}
	return *o.CustomerGroup
}

// GetCustomerGroupOk returns a tuple with the CustomerGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketResponseDataRelationships) GetCustomerGroupOk() (*CustomerResponseDataRelationshipsCustomerGroup, bool) {
	if o == nil || o.CustomerGroup == nil {
		return nil, false
	}
	return o.CustomerGroup, true
}

// HasCustomerGroup returns a boolean if a field has been set.
func (o *MarketResponseDataRelationships) HasCustomerGroup() bool {
	if o != nil && o.CustomerGroup != nil {
		return true
	}

	return false
}

// SetCustomerGroup gets a reference to the given CustomerResponseDataRelationshipsCustomerGroup and assigns it to the CustomerGroup field.
func (o *MarketResponseDataRelationships) SetCustomerGroup(v CustomerResponseDataRelationshipsCustomerGroup) {
	o.CustomerGroup = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *MarketResponseDataRelationships) GetAttachments() AvalaraAccountResponseDataRelationshipsAttachments {
	if o == nil || o.Attachments == nil {
		var ret AvalaraAccountResponseDataRelationshipsAttachments
		return ret
	}
	return *o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketResponseDataRelationships) GetAttachmentsOk() (*AvalaraAccountResponseDataRelationshipsAttachments, bool) {
	if o == nil || o.Attachments == nil {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *MarketResponseDataRelationships) HasAttachments() bool {
	if o != nil && o.Attachments != nil {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given AvalaraAccountResponseDataRelationshipsAttachments and assigns it to the Attachments field.
func (o *MarketResponseDataRelationships) SetAttachments(v AvalaraAccountResponseDataRelationshipsAttachments) {
	o.Attachments = &v
}

func (o MarketResponseDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Merchant != nil {
		toSerialize["merchant"] = o.Merchant
	}
	if o.PriceList != nil {
		toSerialize["price_list"] = o.PriceList
	}
	if o.InventoryModel != nil {
		toSerialize["inventory_model"] = o.InventoryModel
	}
	if o.TaxCalculator != nil {
		toSerialize["tax_calculator"] = o.TaxCalculator
	}
	if o.CustomerGroup != nil {
		toSerialize["customer_group"] = o.CustomerGroup
	}
	if o.Attachments != nil {
		toSerialize["attachments"] = o.Attachments
	}
	return json.Marshal(toSerialize)
}

type NullableMarketResponseDataRelationships struct {
	value *MarketResponseDataRelationships
	isSet bool
}

func (v NullableMarketResponseDataRelationships) Get() *MarketResponseDataRelationships {
	return v.value
}

func (v *NullableMarketResponseDataRelationships) Set(val *MarketResponseDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketResponseDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketResponseDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketResponseDataRelationships(val *MarketResponseDataRelationships) *NullableMarketResponseDataRelationships {
	return &NullableMarketResponseDataRelationships{value: val, isSet: true}
}

func (v NullableMarketResponseDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketResponseDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
