/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 3.0.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// POSTPercentageDiscountPromotions201Response struct for POSTPercentageDiscountPromotions201Response
type POSTPercentageDiscountPromotions201Response struct {
	Data *POSTPercentageDiscountPromotions201ResponseData `json:"data,omitempty"`
}

// NewPOSTPercentageDiscountPromotions201Response instantiates a new POSTPercentageDiscountPromotions201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPOSTPercentageDiscountPromotions201Response() *POSTPercentageDiscountPromotions201Response {
	this := POSTPercentageDiscountPromotions201Response{}
	return &this
}

// NewPOSTPercentageDiscountPromotions201ResponseWithDefaults instantiates a new POSTPercentageDiscountPromotions201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPOSTPercentageDiscountPromotions201ResponseWithDefaults() *POSTPercentageDiscountPromotions201Response {
	this := POSTPercentageDiscountPromotions201Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *POSTPercentageDiscountPromotions201Response) GetData() POSTPercentageDiscountPromotions201ResponseData {
	if o == nil || o.Data == nil {
		var ret POSTPercentageDiscountPromotions201ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *POSTPercentageDiscountPromotions201Response) GetDataOk() (*POSTPercentageDiscountPromotions201ResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *POSTPercentageDiscountPromotions201Response) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given POSTPercentageDiscountPromotions201ResponseData and assigns it to the Data field.
func (o *POSTPercentageDiscountPromotions201Response) SetData(v POSTPercentageDiscountPromotions201ResponseData) {
	o.Data = &v
}

func (o POSTPercentageDiscountPromotions201Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePOSTPercentageDiscountPromotions201Response struct {
	value *POSTPercentageDiscountPromotions201Response
	isSet bool
}

func (v NullablePOSTPercentageDiscountPromotions201Response) Get() *POSTPercentageDiscountPromotions201Response {
	return v.value
}

func (v *NullablePOSTPercentageDiscountPromotions201Response) Set(val *POSTPercentageDiscountPromotions201Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePOSTPercentageDiscountPromotions201Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePOSTPercentageDiscountPromotions201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePOSTPercentageDiscountPromotions201Response(val *POSTPercentageDiscountPromotions201Response) *NullablePOSTPercentageDiscountPromotions201Response {
	return &NullablePOSTPercentageDiscountPromotions201Response{value: val, isSet: true}
}

func (v NullablePOSTPercentageDiscountPromotions201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePOSTPercentageDiscountPromotions201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
