/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 7.3.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ShippingZoneCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShippingZoneCreateData{}

// ShippingZoneCreateData struct for ShippingZoneCreateData
type ShippingZoneCreateData struct {
	// The resource's type
	Type          interface{}                                `json:"type"`
	Attributes    POSTShippingZones201ResponseDataAttributes `json:"attributes"`
	Relationships interface{}                                `json:"relationships,omitempty"`
}

// NewShippingZoneCreateData instantiates a new ShippingZoneCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShippingZoneCreateData(type_ interface{}, attributes POSTShippingZones201ResponseDataAttributes) *ShippingZoneCreateData {
	this := ShippingZoneCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewShippingZoneCreateDataWithDefaults instantiates a new ShippingZoneCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShippingZoneCreateDataWithDefaults() *ShippingZoneCreateData {
	this := ShippingZoneCreateData{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ShippingZoneCreateData) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShippingZoneCreateData) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ShippingZoneCreateData) SetType(v interface{}) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ShippingZoneCreateData) GetAttributes() POSTShippingZones201ResponseDataAttributes {
	if o == nil {
		var ret POSTShippingZones201ResponseDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ShippingZoneCreateData) GetAttributesOk() (*POSTShippingZones201ResponseDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ShippingZoneCreateData) SetAttributes(v POSTShippingZones201ResponseDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShippingZoneCreateData) GetRelationships() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShippingZoneCreateData) GetRelationshipsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return &o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *ShippingZoneCreateData) HasRelationships() bool {
	if o != nil && IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given interface{} and assigns it to the Relationships field.
func (o *ShippingZoneCreateData) SetRelationships(v interface{}) {
	o.Relationships = v
}

func (o ShippingZoneCreateData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShippingZoneCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	toSerialize["attributes"] = o.Attributes
	if o.Relationships != nil {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

type NullableShippingZoneCreateData struct {
	value *ShippingZoneCreateData
	isSet bool
}

func (v NullableShippingZoneCreateData) Get() *ShippingZoneCreateData {
	return v.value
}

func (v *NullableShippingZoneCreateData) Set(val *ShippingZoneCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingZoneCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingZoneCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingZoneCreateData(val *ShippingZoneCreateData) *NullableShippingZoneCreateData {
	return &NullableShippingZoneCreateData{value: val, isSet: true}
}

func (v NullableShippingZoneCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingZoneCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
