/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 7.6.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the InventoryStockLocationCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryStockLocationCreateData{}

// InventoryStockLocationCreateData struct for InventoryStockLocationCreateData
type InventoryStockLocationCreateData struct {
	// The resource's type
	Type          interface{}                                          `json:"type"`
	Attributes    POSTInventoryStockLocations201ResponseDataAttributes `json:"attributes"`
	Relationships *InventoryReturnLocationCreateDataRelationships      `json:"relationships,omitempty"`
}

// NewInventoryStockLocationCreateData instantiates a new InventoryStockLocationCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryStockLocationCreateData(type_ interface{}, attributes POSTInventoryStockLocations201ResponseDataAttributes) *InventoryStockLocationCreateData {
	this := InventoryStockLocationCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewInventoryStockLocationCreateDataWithDefaults instantiates a new InventoryStockLocationCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryStockLocationCreateDataWithDefaults() *InventoryStockLocationCreateData {
	this := InventoryStockLocationCreateData{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InventoryStockLocationCreateData) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InventoryStockLocationCreateData) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InventoryStockLocationCreateData) SetType(v interface{}) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *InventoryStockLocationCreateData) GetAttributes() POSTInventoryStockLocations201ResponseDataAttributes {
	if o == nil {
		var ret POSTInventoryStockLocations201ResponseDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *InventoryStockLocationCreateData) GetAttributesOk() (*POSTInventoryStockLocations201ResponseDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *InventoryStockLocationCreateData) SetAttributes(v POSTInventoryStockLocations201ResponseDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *InventoryStockLocationCreateData) GetRelationships() InventoryReturnLocationCreateDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret InventoryReturnLocationCreateDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockLocationCreateData) GetRelationshipsOk() (*InventoryReturnLocationCreateDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *InventoryStockLocationCreateData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given InventoryReturnLocationCreateDataRelationships and assigns it to the Relationships field.
func (o *InventoryStockLocationCreateData) SetRelationships(v InventoryReturnLocationCreateDataRelationships) {
	o.Relationships = &v
}

func (o InventoryStockLocationCreateData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryStockLocationCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

type NullableInventoryStockLocationCreateData struct {
	value *InventoryStockLocationCreateData
	isSet bool
}

func (v NullableInventoryStockLocationCreateData) Get() *InventoryStockLocationCreateData {
	return v.value
}

func (v *NullableInventoryStockLocationCreateData) Set(val *InventoryStockLocationCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryStockLocationCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryStockLocationCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryStockLocationCreateData(val *InventoryStockLocationCreateData) *NullableInventoryStockLocationCreateData {
	return &NullableInventoryStockLocationCreateData{value: val, isSet: true}
}

func (v NullableInventoryStockLocationCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryStockLocationCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
