/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 4.1.3
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes{}

// PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes struct for PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes
type PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes struct {
	// The code of the associated SKU.
	SkuCode interface{} `json:"sku_code,omitempty"`
	// The code of the associated bundle.
	BundleCode interface{} `json:"bundle_code,omitempty"`
	// The subscription item quantity.
	Quantity interface{} `json:"quantity,omitempty"`
	// The unit amount of the subscription item, in cents.
	UnitAmountCents interface{} `json:"unit_amount_cents,omitempty"`
	// A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
	Reference interface{} `json:"reference,omitempty"`
	// Any identifier of the third party system that defines the reference code
	ReferenceOrigin interface{} `json:"reference_origin,omitempty"`
	// Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
	Metadata interface{} `json:"metadata,omitempty"`
}

// NewPATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes instantiates a new PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes() *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes {
	this := PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes{}
	return &this
}

// NewPATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributesWithDefaults instantiates a new PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributesWithDefaults() *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes {
	this := PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes{}
	return &this
}

// GetSkuCode returns the SkuCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetSkuCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SkuCode
}

// GetSkuCodeOk returns a tuple with the SkuCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetSkuCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SkuCode) {
		return nil, false
	}
	return &o.SkuCode, true
}

// HasSkuCode returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasSkuCode() bool {
	if o != nil && IsNil(o.SkuCode) {
		return true
	}

	return false
}

// SetSkuCode gets a reference to the given interface{} and assigns it to the SkuCode field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetSkuCode(v interface{}) {
	o.SkuCode = v
}

// GetBundleCode returns the BundleCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetBundleCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.BundleCode
}

// GetBundleCodeOk returns a tuple with the BundleCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetBundleCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.BundleCode) {
		return nil, false
	}
	return &o.BundleCode, true
}

// HasBundleCode returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasBundleCode() bool {
	if o != nil && IsNil(o.BundleCode) {
		return true
	}

	return false
}

// SetBundleCode gets a reference to the given interface{} and assigns it to the BundleCode field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetBundleCode(v interface{}) {
	o.BundleCode = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetQuantity() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetQuantityOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return &o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasQuantity() bool {
	if o != nil && IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given interface{} and assigns it to the Quantity field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetQuantity(v interface{}) {
	o.Quantity = v
}

// GetUnitAmountCents returns the UnitAmountCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetUnitAmountCents() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UnitAmountCents
}

// GetUnitAmountCentsOk returns a tuple with the UnitAmountCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetUnitAmountCentsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UnitAmountCents) {
		return nil, false
	}
	return &o.UnitAmountCents, true
}

// HasUnitAmountCents returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasUnitAmountCents() bool {
	if o != nil && IsNil(o.UnitAmountCents) {
		return true
	}

	return false
}

// SetUnitAmountCents gets a reference to the given interface{} and assigns it to the UnitAmountCents field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetUnitAmountCents(v interface{}) {
	o.UnitAmountCents = v
}

// GetReference returns the Reference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetReference() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetReferenceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return &o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasReference() bool {
	if o != nil && IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given interface{} and assigns it to the Reference field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetReference(v interface{}) {
	o.Reference = v
}

// GetReferenceOrigin returns the ReferenceOrigin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetReferenceOrigin() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ReferenceOrigin
}

// GetReferenceOriginOk returns a tuple with the ReferenceOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetReferenceOriginOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ReferenceOrigin) {
		return nil, false
	}
	return &o.ReferenceOrigin, true
}

// HasReferenceOrigin returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasReferenceOrigin() bool {
	if o != nil && IsNil(o.ReferenceOrigin) {
		return true
	}

	return false
}

// SetReferenceOrigin gets a reference to the given interface{} and assigns it to the ReferenceOrigin field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetReferenceOrigin(v interface{}) {
	o.ReferenceOrigin = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) HasMetadata() bool {
	if o != nil && IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) SetMetadata(v interface{}) {
	o.Metadata = v
}

func (o PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SkuCode != nil {
		toSerialize["sku_code"] = o.SkuCode
	}
	if o.BundleCode != nil {
		toSerialize["bundle_code"] = o.BundleCode
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	if o.UnitAmountCents != nil {
		toSerialize["unit_amount_cents"] = o.UnitAmountCents
	}
	if o.Reference != nil {
		toSerialize["reference"] = o.Reference
	}
	if o.ReferenceOrigin != nil {
		toSerialize["reference_origin"] = o.ReferenceOrigin
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes struct {
	value *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes
	isSet bool
}

func (v NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) Get() *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes {
	return v.value
}

func (v *NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) Set(val *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes(val *PATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) *NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes {
	return &NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes{value: val, isSet: true}
}

func (v NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePATCHOrderSubscriptionItemsOrderSubscriptionItemIdRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
