/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 7.3.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the POSTBundles201ResponseDataRelationshipsSkusData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &POSTBundles201ResponseDataRelationshipsSkusData{}

// POSTBundles201ResponseDataRelationshipsSkusData struct for POSTBundles201ResponseDataRelationshipsSkusData
type POSTBundles201ResponseDataRelationshipsSkusData struct {
	// The resource's type
	Type interface{} `json:"type,omitempty"`
	// The resource ID
	Id interface{} `json:"id,omitempty"`
}

// NewPOSTBundles201ResponseDataRelationshipsSkusData instantiates a new POSTBundles201ResponseDataRelationshipsSkusData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPOSTBundles201ResponseDataRelationshipsSkusData() *POSTBundles201ResponseDataRelationshipsSkusData {
	this := POSTBundles201ResponseDataRelationshipsSkusData{}
	return &this
}

// NewPOSTBundles201ResponseDataRelationshipsSkusDataWithDefaults instantiates a new POSTBundles201ResponseDataRelationshipsSkusData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPOSTBundles201ResponseDataRelationshipsSkusDataWithDefaults() *POSTBundles201ResponseDataRelationshipsSkusData {
	this := POSTBundles201ResponseDataRelationshipsSkusData{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *POSTBundles201ResponseDataRelationshipsSkusData) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *POSTBundles201ResponseDataRelationshipsSkusData) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *POSTBundles201ResponseDataRelationshipsSkusData) HasType() bool {
	if o != nil && IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given interface{} and assigns it to the Type field.
func (o *POSTBundles201ResponseDataRelationshipsSkusData) SetType(v interface{}) {
	o.Type = v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *POSTBundles201ResponseDataRelationshipsSkusData) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *POSTBundles201ResponseDataRelationshipsSkusData) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *POSTBundles201ResponseDataRelationshipsSkusData) HasId() bool {
	if o != nil && IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given interface{} and assigns it to the Id field.
func (o *POSTBundles201ResponseDataRelationshipsSkusData) SetId(v interface{}) {
	o.Id = v
}

func (o POSTBundles201ResponseDataRelationshipsSkusData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o POSTBundles201ResponseDataRelationshipsSkusData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePOSTBundles201ResponseDataRelationshipsSkusData struct {
	value *POSTBundles201ResponseDataRelationshipsSkusData
	isSet bool
}

func (v NullablePOSTBundles201ResponseDataRelationshipsSkusData) Get() *POSTBundles201ResponseDataRelationshipsSkusData {
	return v.value
}

func (v *NullablePOSTBundles201ResponseDataRelationshipsSkusData) Set(val *POSTBundles201ResponseDataRelationshipsSkusData) {
	v.value = val
	v.isSet = true
}

func (v NullablePOSTBundles201ResponseDataRelationshipsSkusData) IsSet() bool {
	return v.isSet
}

func (v *NullablePOSTBundles201ResponseDataRelationshipsSkusData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePOSTBundles201ResponseDataRelationshipsSkusData(val *POSTBundles201ResponseDataRelationshipsSkusData) *NullablePOSTBundles201ResponseDataRelationshipsSkusData {
	return &NullablePOSTBundles201ResponseDataRelationshipsSkusData{value: val, isSet: true}
}

func (v NullablePOSTBundles201ResponseDataRelationshipsSkusData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePOSTBundles201ResponseDataRelationshipsSkusData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
