/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 3.0.0
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GETParcels200ResponseDataInnerRelationships struct for GETParcels200ResponseDataInnerRelationships
type GETParcels200ResponseDataInnerRelationships struct {
	Shipment *GETAddresses200ResponseDataInnerRelationshipsGeocoder `json:"shipment,omitempty"`
	Package *GETAddresses200ResponseDataInnerRelationshipsGeocoder `json:"package,omitempty"`
	ParcelLineItems *GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods `json:"parcel_line_items,omitempty"`
	Attachments *GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods `json:"attachments,omitempty"`
	Events *GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods `json:"events,omitempty"`
}

// NewGETParcels200ResponseDataInnerRelationships instantiates a new GETParcels200ResponseDataInnerRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGETParcels200ResponseDataInnerRelationships() *GETParcels200ResponseDataInnerRelationships {
	this := GETParcels200ResponseDataInnerRelationships{}
	return &this
}

// NewGETParcels200ResponseDataInnerRelationshipsWithDefaults instantiates a new GETParcels200ResponseDataInnerRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGETParcels200ResponseDataInnerRelationshipsWithDefaults() *GETParcels200ResponseDataInnerRelationships {
	this := GETParcels200ResponseDataInnerRelationships{}
	return &this
}

// GetShipment returns the Shipment field value if set, zero value otherwise.
func (o *GETParcels200ResponseDataInnerRelationships) GetShipment() GETAddresses200ResponseDataInnerRelationshipsGeocoder {
	if o == nil || o.Shipment == nil {
		var ret GETAddresses200ResponseDataInnerRelationshipsGeocoder
		return ret
	}
	return *o.Shipment
}

// GetShipmentOk returns a tuple with the Shipment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GETParcels200ResponseDataInnerRelationships) GetShipmentOk() (*GETAddresses200ResponseDataInnerRelationshipsGeocoder, bool) {
	if o == nil || o.Shipment == nil {
		return nil, false
	}
	return o.Shipment, true
}

// HasShipment returns a boolean if a field has been set.
func (o *GETParcels200ResponseDataInnerRelationships) HasShipment() bool {
	if o != nil && o.Shipment != nil {
		return true
	}

	return false
}

// SetShipment gets a reference to the given GETAddresses200ResponseDataInnerRelationshipsGeocoder and assigns it to the Shipment field.
func (o *GETParcels200ResponseDataInnerRelationships) SetShipment(v GETAddresses200ResponseDataInnerRelationshipsGeocoder) {
	o.Shipment = &v
}

// GetPackage returns the Package field value if set, zero value otherwise.
func (o *GETParcels200ResponseDataInnerRelationships) GetPackage() GETAddresses200ResponseDataInnerRelationshipsGeocoder {
	if o == nil || o.Package == nil {
		var ret GETAddresses200ResponseDataInnerRelationshipsGeocoder
		return ret
	}
	return *o.Package
}

// GetPackageOk returns a tuple with the Package field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GETParcels200ResponseDataInnerRelationships) GetPackageOk() (*GETAddresses200ResponseDataInnerRelationshipsGeocoder, bool) {
	if o == nil || o.Package == nil {
		return nil, false
	}
	return o.Package, true
}

// HasPackage returns a boolean if a field has been set.
func (o *GETParcels200ResponseDataInnerRelationships) HasPackage() bool {
	if o != nil && o.Package != nil {
		return true
	}

	return false
}

// SetPackage gets a reference to the given GETAddresses200ResponseDataInnerRelationshipsGeocoder and assigns it to the Package field.
func (o *GETParcels200ResponseDataInnerRelationships) SetPackage(v GETAddresses200ResponseDataInnerRelationshipsGeocoder) {
	o.Package = &v
}

// GetParcelLineItems returns the ParcelLineItems field value if set, zero value otherwise.
func (o *GETParcels200ResponseDataInnerRelationships) GetParcelLineItems() GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods {
	if o == nil || o.ParcelLineItems == nil {
		var ret GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods
		return ret
	}
	return *o.ParcelLineItems
}

// GetParcelLineItemsOk returns a tuple with the ParcelLineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GETParcels200ResponseDataInnerRelationships) GetParcelLineItemsOk() (*GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods, bool) {
	if o == nil || o.ParcelLineItems == nil {
		return nil, false
	}
	return o.ParcelLineItems, true
}

// HasParcelLineItems returns a boolean if a field has been set.
func (o *GETParcels200ResponseDataInnerRelationships) HasParcelLineItems() bool {
	if o != nil && o.ParcelLineItems != nil {
		return true
	}

	return false
}

// SetParcelLineItems gets a reference to the given GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods and assigns it to the ParcelLineItems field.
func (o *GETParcels200ResponseDataInnerRelationships) SetParcelLineItems(v GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods) {
	o.ParcelLineItems = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *GETParcels200ResponseDataInnerRelationships) GetAttachments() GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods {
	if o == nil || o.Attachments == nil {
		var ret GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods
		return ret
	}
	return *o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GETParcels200ResponseDataInnerRelationships) GetAttachmentsOk() (*GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods, bool) {
	if o == nil || o.Attachments == nil {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *GETParcels200ResponseDataInnerRelationships) HasAttachments() bool {
	if o != nil && o.Attachments != nil {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods and assigns it to the Attachments field.
func (o *GETParcels200ResponseDataInnerRelationships) SetAttachments(v GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods) {
	o.Attachments = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *GETParcels200ResponseDataInnerRelationships) GetEvents() GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods {
	if o == nil || o.Events == nil {
		var ret GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods
		return ret
	}
	return *o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GETParcels200ResponseDataInnerRelationships) GetEventsOk() (*GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods, bool) {
	if o == nil || o.Events == nil {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *GETParcels200ResponseDataInnerRelationships) HasEvents() bool {
	if o != nil && o.Events != nil {
		return true
	}

	return false
}

// SetEvents gets a reference to the given GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods and assigns it to the Events field.
func (o *GETParcels200ResponseDataInnerRelationships) SetEvents(v GETAdyenGateways200ResponseDataInnerRelationshipsPaymentMethods) {
	o.Events = &v
}

func (o GETParcels200ResponseDataInnerRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Shipment != nil {
		toSerialize["shipment"] = o.Shipment
	}
	if o.Package != nil {
		toSerialize["package"] = o.Package
	}
	if o.ParcelLineItems != nil {
		toSerialize["parcel_line_items"] = o.ParcelLineItems
	}
	if o.Attachments != nil {
		toSerialize["attachments"] = o.Attachments
	}
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	return json.Marshal(toSerialize)
}

type NullableGETParcels200ResponseDataInnerRelationships struct {
	value *GETParcels200ResponseDataInnerRelationships
	isSet bool
}

func (v NullableGETParcels200ResponseDataInnerRelationships) Get() *GETParcels200ResponseDataInnerRelationships {
	return v.value
}

func (v *NullableGETParcels200ResponseDataInnerRelationships) Set(val *GETParcels200ResponseDataInnerRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGETParcels200ResponseDataInnerRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGETParcels200ResponseDataInnerRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGETParcels200ResponseDataInnerRelationships(val *GETParcels200ResponseDataInnerRelationships) *NullableGETParcels200ResponseDataInnerRelationships {
	return &NullableGETParcels200ResponseDataInnerRelationships{value: val, isSet: true}
}

func (v NullableGETParcels200ResponseDataInnerRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGETParcels200ResponseDataInnerRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


