/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 3.0.1
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ExternalPromotionResponseDataRelationshipsSkuListPromotionRule struct for ExternalPromotionResponseDataRelationshipsSkuListPromotionRule
type ExternalPromotionResponseDataRelationshipsSkuListPromotionRule struct {
	Links *AddressResponseDataRelationshipsGeocoderLinks                      `json:"links,omitempty"`
	Data  *ExternalPromotionResponseDataRelationshipsSkuListPromotionRuleData `json:"data,omitempty"`
}

// NewExternalPromotionResponseDataRelationshipsSkuListPromotionRule instantiates a new ExternalPromotionResponseDataRelationshipsSkuListPromotionRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalPromotionResponseDataRelationshipsSkuListPromotionRule() *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule {
	this := ExternalPromotionResponseDataRelationshipsSkuListPromotionRule{}
	return &this
}

// NewExternalPromotionResponseDataRelationshipsSkuListPromotionRuleWithDefaults instantiates a new ExternalPromotionResponseDataRelationshipsSkuListPromotionRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalPromotionResponseDataRelationshipsSkuListPromotionRuleWithDefaults() *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule {
	this := ExternalPromotionResponseDataRelationshipsSkuListPromotionRule{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) GetLinks() AddressResponseDataRelationshipsGeocoderLinks {
	if o == nil || o.Links == nil {
		var ret AddressResponseDataRelationshipsGeocoderLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) GetLinksOk() (*AddressResponseDataRelationshipsGeocoderLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given AddressResponseDataRelationshipsGeocoderLinks and assigns it to the Links field.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) SetLinks(v AddressResponseDataRelationshipsGeocoderLinks) {
	o.Links = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) GetData() ExternalPromotionResponseDataRelationshipsSkuListPromotionRuleData {
	if o == nil || o.Data == nil {
		var ret ExternalPromotionResponseDataRelationshipsSkuListPromotionRuleData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) GetDataOk() (*ExternalPromotionResponseDataRelationshipsSkuListPromotionRuleData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ExternalPromotionResponseDataRelationshipsSkuListPromotionRuleData and assigns it to the Data field.
func (o *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) SetData(v ExternalPromotionResponseDataRelationshipsSkuListPromotionRuleData) {
	o.Data = &v
}

func (o ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule struct {
	value *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule
	isSet bool
}

func (v NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule) Get() *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule {
	return v.value
}

func (v *NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule) Set(val *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule(val *ExternalPromotionResponseDataRelationshipsSkuListPromotionRule) *NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule {
	return &NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule{value: val, isSet: true}
}

func (v NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalPromotionResponseDataRelationshipsSkuListPromotionRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
