/*
Commerce Layer API

Headless Commerce for Global Brands.

API version: 3.0.2
Contact: support@commercelayer.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GoogleGeocoderCreateData struct for GoogleGeocoderCreateData
type GoogleGeocoderCreateData struct {
	// The resource's type
	Type          string                                       `json:"type"`
	Attributes    POSTGoogleGeocoders201ResponseDataAttributes `json:"attributes"`
	Relationships map[string]interface{}                       `json:"relationships,omitempty"`
}

// NewGoogleGeocoderCreateData instantiates a new GoogleGeocoderCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleGeocoderCreateData(type_ string, attributes POSTGoogleGeocoders201ResponseDataAttributes) *GoogleGeocoderCreateData {
	this := GoogleGeocoderCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewGoogleGeocoderCreateDataWithDefaults instantiates a new GoogleGeocoderCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleGeocoderCreateDataWithDefaults() *GoogleGeocoderCreateData {
	this := GoogleGeocoderCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *GoogleGeocoderCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GoogleGeocoderCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GoogleGeocoderCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *GoogleGeocoderCreateData) GetAttributes() POSTGoogleGeocoders201ResponseDataAttributes {
	if o == nil {
		var ret POSTGoogleGeocoders201ResponseDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GoogleGeocoderCreateData) GetAttributesOk() (*POSTGoogleGeocoders201ResponseDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GoogleGeocoderCreateData) SetAttributes(v POSTGoogleGeocoders201ResponseDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *GoogleGeocoderCreateData) GetRelationships() map[string]interface{} {
	if o == nil || o.Relationships == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleGeocoderCreateData) GetRelationshipsOk() (map[string]interface{}, bool) {
	if o == nil || o.Relationships == nil {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *GoogleGeocoderCreateData) HasRelationships() bool {
	if o != nil && o.Relationships != nil {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given map[string]interface{} and assigns it to the Relationships field.
func (o *GoogleGeocoderCreateData) SetRelationships(v map[string]interface{}) {
	o.Relationships = v
}

func (o GoogleGeocoderCreateData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["attributes"] = o.Attributes
	}
	if o.Relationships != nil {
		toSerialize["relationships"] = o.Relationships
	}
	return json.Marshal(toSerialize)
}

type NullableGoogleGeocoderCreateData struct {
	value *GoogleGeocoderCreateData
	isSet bool
}

func (v NullableGoogleGeocoderCreateData) Get() *GoogleGeocoderCreateData {
	return v.value
}

func (v *NullableGoogleGeocoderCreateData) Set(val *GoogleGeocoderCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleGeocoderCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleGeocoderCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleGeocoderCreateData(val *GoogleGeocoderCreateData) *NullableGoogleGeocoderCreateData {
	return &NullableGoogleGeocoderCreateData{value: val, isSet: true}
}

func (v NullableGoogleGeocoderCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleGeocoderCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
